import type { Contact } from "./types";

export const SEED_CONTACTS: Contact[] = [
  {
    id: "c-1001",
    salutation: "Frau",
    title: "Dr.",
    firstName: "Lena",
    lastName: "Hoffmann",
    position: "Head of Treasury",
    department: "Finance",
    company: "Nordbank AG",
    street: "Ballindamm 27",
    postalCode: "20095",
    city: "Hamburg",
    country: "Deutschland",
    channels: [
      { id: "ch-1", kind: "phone", label: "Geschäftlich", value: "+49 40 123 456-0" },
      { id: "ch-2", kind: "mobile", label: "Privat", value: "+49 151 2345 6789" },
      { id: "ch-3", kind: "email", label: "Geschäftlich", value: "l.hoffmann@nordbank.de" },
    ],
    notes: "Bevorzugt Termine am Vormittag. Entscheidet über Liquiditätsprodukte.",
    createdAt: "2026-01-12T09:00:00.000Z",
    updatedAt: "2026-05-28T11:20:00.000Z",
  },
  {
    id: "c-1002",
    salutation: "Herr",
    title: "",
    firstName: "Marco",
    lastName: "Bertsch",
    position: "Procurement Lead",
    department: "Einkauf",
    company: "Helvetia Logistics GmbH",
    street: "Industriestraße 4",
    postalCode: "70565",
    city: "Stuttgart",
    country: "Deutschland",
    channels: [
      { id: "ch-4", kind: "phone", label: "Zentrale", value: "+49 711 998 22-100" },
      { id: "ch-5", kind: "mobile", label: "Geschäftlich", value: "+49 160 4455 221" },
      { id: "ch-6", kind: "email", label: "Geschäftlich", value: "m.bertsch@helvetia-log.com" },
      { id: "ch-7", kind: "email", label: "Rechnung", value: "rechnung@helvetia-log.com" },
    ],
    notes: "Reagiert schneller per E-Mail als telefonisch.",
    createdAt: "2026-02-03T14:30:00.000Z",
    updatedAt: "2026-06-01T08:05:00.000Z",
  },
  {
    id: "c-1003",
    salutation: "Frau",
    title: "Prof.",
    firstName: "Sofia",
    lastName: "Lindqvist",
    position: "CFO",
    department: "Geschäftsführung",
    company: "Aurora Pay Solutions",
    street: "Friedrichstraße 110",
    postalCode: "10117",
    city: "Berlin",
    country: "Deutschland",
    channels: [
      { id: "ch-8", kind: "mobile", label: "Geschäftlich", value: "+49 170 5566 778" },
      { id: "ch-9", kind: "email", label: "Geschäftlich", value: "s.lindqvist@aurorapay.io" },
    ],
    notes: "Strategischer Kontakt. Quartalsreview im Juli geplant.",
    createdAt: "2026-03-18T10:15:00.000Z",
    updatedAt: "2026-06-10T16:45:00.000Z",
  },
  {
    id: "c-1004",
    salutation: "Herr",
    title: "",
    firstName: "Jonas",
    lastName: "Keller",
    position: "IT-Administrator",
    department: "IT",
    company: "Syscon Network",
    street: "Hauptstraße 12",
    postalCode: "40210",
    city: "Düsseldorf",
    country: "Deutschland",
    channels: [
      { id: "ch-10", kind: "phone", label: "Geschäftlich", value: "+49 211 700 88-12" },
      { id: "ch-11", kind: "email", label: "Geschäftlich", value: "j.keller@syscon-network.de" },
    ],
    notes: "",
    createdAt: "2026-04-22T07:50:00.000Z",
    updatedAt: "2026-04-22T07:50:00.000Z",
  },
];
